<a href="https://colab.research.google.com/github/godlyghostgamer/ML-Model/blob/main/ml_model_ipnyb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Replace '/content/sample_data/r24ea072.xlsx' with the path you copied
file_path = '/content/sample_data/r24eq100.xlsx'

# Load the Excel file into a pandas DataFrame
try:
    df = pd.read_excel(file_path)
    print("DataFrame loaded successfully!")
    # Display the first 5 rows of the DataFrame
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file was not found at {file_path}")
except Exception as e:
    print(f"An error occurred: {e}")

DataFrame loaded successfully!

,SUMMARY OUTPUT,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Regression Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Multiple R,0.582515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R Square,0.339324,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjusted R Square,0.25674,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Define the desired path for the CSV file
csv_file_path = '/content/r23ea174.csv'

# Convert the DataFrame to a CSV file
df.to_csv(csv_file_path, index=False)

print(f"DataFrame successfully saved to {csv_file_path}")

DataFrame successfully saved to /content/r23ea174.csv

In [ ]:
# Define the path to the CSV file
csv_file_path = '/content/new_independent_file.csv'

# Load the CSV file into a pandas DataFrame
try:
    df_csv = pd.read_csv(csv_file_path)
    print("DataFrame loaded from CSV successfully!")
    # Display the first 5 rows of the new DataFrame
    display(df_csv.head())
except FileNotFoundError:
    print(f"Error: The file was not found at {csv_file_path}")
except Exception as e:
    print(f"An error occurred: {e}")

DataFrame loaded from CSV successfully!

   col1 col2
0     1    A
1     2    B
2     3    C
3     4    D

In [ ]:
import pandas as pd

# Create a new DataFrame with sample data
data = {'colA': [10, 20, 30],
        'colB': ['X', 'Y', 'Z']}
m_df = pd.DataFrame(data)

# Define the desired path for the new CSV file
m_csv_file_path = '/content/m.csv'

# Convert the new DataFrame to a CSV file
m_df.to_csv(m_csv_file_path, index=False)

print(f"New independent CSV file successfully created at {m_csv_file_path}")
display(m_df.head())

New independent CSV file successfully created at /content/m.csv

   colA colB
0    10    X
1    20    Y
2    30    Z

In [ ]:
# Define the path to the CSV file
csv_file_path = '/content/m.csv'

# Load the CSV file into a pandas DataFrame
try:
    df_csv = pd.read_csv(csv_file_path)
    print("DataFrame loaded from CSV successfully!")
    # Display the first 5 rows of the new DataFrame
    display(df_csv.head())
except FileNotFoundError:
    print(f"Error: The file was not found at {csv_file_path}")
except Exception as e:
    print(f"An error occurred: {e}")

DataFrame loaded from CSV successfully!

   colA colB
0    10    X
1    20    Y
2    30    Z

In [ ]:
# Add one more row with sample data
# The data in the list should match the number and type of existing columns
new_row_data = [99, 'Z9']
df_csv.loc[len(df_csv)] = new_row_data

# Add one more column with sample data
# The list should have a value for each row in the DataFrame
new_column_data = [i for i in range(len(df_csv))]
df_csv['New_Sample_Column'] = new_column_data

print("DataFrame after adding one more row and one more column:")
display(df_csv.tail())

ValueError: cannot set a row with mismatched columns

In [ ]:
display(df_csv.tail())

        colA      colB  Random_Column_1  Random_Column_2
0  10.000000         X               53               88
1  20.000000         Y               81               83
2  30.000000         Z               93               65
3   0.177001  0.648172               87               51
4   0.373451  0.523341                0               41

# Task
Perform `head()`, `tail()`, `shape`, `info()`, `describe()`, `iloc`, `dropna`, `drop`, indexing, and slicing on the dataframe `m` in separate cells.

## Apply `head()`

### Subtask:
Show the first few rows of the DataFrame.

**Reasoning**:
Use the head() method to display the first few rows of the DataFrame as instructed.

In [ ]:
display(m_df.head())

   colA colB
0    10    X
1    20    Y
2    30    Z

## Apply `tail()`

### Subtask:
Show the last few rows of the DataFrame.

**Reasoning**:
Use the tail() method to display the last few rows of the DataFrame as requested in the subtask instructions.

In [ ]:
display(m_df.tail())

   colA colB
0    10    X
1    20    Y
2    30    Z

## Get `shape`

### Subtask:
Display the dimensions (rows, columns) of the DataFrame.

**Reasoning**:
Access the `shape` attribute of the `m_df` DataFrame to get its dimensions and print it.

In [ ]:
display(df_csv.tail())

**Reasoning**:
Use the `tail()` method to display the last few rows of the `df_csv` DataFrame as requested in the subtask instructions.

## Apply `tail()`

### Subtask:
Show the last few rows of the DataFrame.

In [ ]:
display(df_csv.head())

        colA      colB  Random_Column_1  Random_Column_2
0  10.000000         X               53               88
1  20.000000         Y               81               83
2  30.000000         Z               93               65
3   0.177001  0.648172               87               51
4   0.373451  0.523341                0               41

**Reasoning**:
Use the `head()` method to display the first few rows of the `df_csv` DataFrame as requested in the plan.

## Apply `head()`

### Subtask:
Show the first few rows of the DataFrame.

In [ ]:
print(m_df.shape)

(3, 2)

## Apply `info()`

### Subtask:
Show a concise summary of the DataFrame, including data types and non-null values.

**Reasoning**:
Call the `.info()` method on the `m_df` DataFrame to display a concise summary, including data types and non-null values.

In [ ]:
m_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   colA    3 non-null      int64
 1   colB    3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

## Apply `describe()`

### Subtask:
Generate descriptive statistics of the DataFrame.

**Reasoning**:
Call the .describe() method on the m_df DataFrame and display the output to generate descriptive statistics.

In [ ]:
display(m_df.describe())

       colA
count   3.0
mean   20.0
std    10.0
min    10.0
25%    15.0
50%    20.0
75%    25.0
max    30.0

## Apply `iloc`

### Subtask:
Demonstrate integer-location based indexing.

**Reasoning**:
Select the first row, a specific value in the second row and first column, and a slice of rows and all columns from the `m_df` DataFrame using `iloc` as requested by the instructions.

In [ ]:
# Select the first row
first_row = m_df.iloc[0]
print("First row:")
display(first_row)

# Select the value in the second row and the first column
value_second_row_first_col = m_df.iloc[1, 0]
print("\nValue in the second row and first column:")
display(value_second_row_first_col)

# Select a slice of rows (0 to 1) and all columns
slice_of_df = m_df.iloc[0:2, :]
print("\nSlice of rows 0 to 1 and all columns:")
display(slice_of_df)

First row:

colA    10
colB     X
Name: 0, dtype: object

Value in the second row and first column:

np.int64(20)

Slice of rows 0 to 1 and all columns:

   colA colB
0    10    X
1    20    Y

## Apply `dropna()`

### Subtask:
Show how to remove rows with missing values.

**Reasoning**:
Create a copy of the DataFrame, introduce missing values, and display the DataFrame with missing values.

In [ ]:
import numpy as np

# Create a copy of the DataFrame m_df
df_with_na = m_df.copy()

# Introduce missing values (NaN)
# Assign NaN to the cell at row index 1, column 'colA'
df_with_na.loc[1, 'colA'] = np.nan
# Assign NaN to the cell at row index 2, column 'colB'
df_with_na.loc[2, 'colB'] = np.nan

print("DataFrame after introducing missing values:")
display(df_with_na)

DataFrame after introducing missing values:

   colA colB
0  10.0    X
1   NaN    Y
2  30.0  NaN

**Reasoning**:
Remove rows with missing values from the DataFrame and display the resulting DataFrame.

In [ ]:
# Apply dropna() to remove rows with missing values
df_dropped_na = df_with_na.dropna()

print("\nDataFrame after removing rows with missing values:")
display(df_dropped_na)

DataFrame after removing rows with missing values:

   colA colB
0  10.0    X

## Apply `drop`

### Subtask:
Demonstrate how to drop specific rows or columns.

**Reasoning**:
Create a copy of the m_df DataFrame, drop the row with index 1, drop the column 'colB', and display the result after each drop operation.

In [ ]:
# Create a copy of the m_df DataFrame to avoid modifying the original
df_copy = m_df.copy()

# Drop the row with index 1
df_copy_row_dropped = df_copy.drop(1)
print("DataFrame after dropping row with index 1:")
display(df_copy_row_dropped)

# Drop the column named 'colB' from the copied DataFrame
df_copy_col_dropped = df_copy.drop(columns=['colB'])
print("\nDataFrame after dropping column 'colB':")
display(df_copy_col_dropped)

DataFrame after dropping row with index 1:

   colA colB
0    10    X
2    30    Z

DataFrame after dropping column 'colB':

   colA
0    10
1    20
2    30

## Perform indexing

### Subtask:
Show how to select data using labels.

**Reasoning**:
Select the row with index 0 from the `m_df` DataFrame using label-based indexing (`.loc`).

In [ ]:
# Select the row with index 0
first_row_loc = m_df.loc[0]
print("Row with index 0:")
display(first_row_loc)

Row with index 0:

colA    10
colB     X
Name: 0, dtype: object

**Reasoning**:
Select the value in the first row and the column 'colA' from the `m_df` DataFrame using label-based indexing (`.loc`) and select a slice of rows from index 0 to 1 (inclusive) and the column 'colB' from the `m_df` DataFrame using label-based indexing (`.loc`).

In [ ]:
# Select the value in the first row and the column 'colA'
value_first_row_colA = m_df.loc[0, 'colA']
print("\nValue in the first row and 'colA' column:")
display(value_first_row_colA)

# Select a slice of rows from index 0 to 1 (inclusive) and the column 'colB'
slice_rows_0_to_1_colB = m_df.loc[0:1, 'colB']
print("\nSlice of rows 0 to 1 (inclusive) and 'colB' column:")
display(slice_rows_0_to_1_colB)

Value in the first row and 'colA' column:

np.int64(10)

Slice of rows 0 to 1 (inclusive) and 'colB' column:

0    X
1    Y
Name: colB, dtype: object

## Perform slicing

### Subtask:
Demonstrate how to select a range of data.

**Reasoning**:
Demonstrate how to select a range of data using slicing with both integer-location and label-based methods as requested in the instructions.

In [ ]:
# 1. Select a slice of rows from the beginning up to index 2 (exclusive) and all columns using integer-location based slicing (iloc)
slice_iloc_rows = m_df.iloc[:2, :]
print("Slice of rows from beginning up to index 2 (exclusive) and all columns (iloc):")
display(slice_iloc_rows)

# 2. Select a slice of all rows and columns from 'colA' up to 'colB' (inclusive) using label-based slicing (loc)
slice_loc_cols = m_df.loc[:, 'colA':'colB']
print("\nSlice of all rows and columns from 'colA' up to 'colB' (inclusive) (loc):")
display(slice_loc_cols)

# 3. Select a slice of rows from index 1 onwards and the column 'colB' using integer-location based slicing (iloc)
slice_iloc_rows_cols = m_df.iloc[1:, 1]
print("\nSlice of rows from index 1 onwards and column 'colB' (iloc):")
display(slice_iloc_rows_cols)

Slice of rows from beginning up to index 2 (exclusive) and all columns (iloc):

   colA colB
0    10    X
1    20    Y

Slice of all rows and columns from 'colA' up to 'colB' (inclusive) (loc):

   colA colB
0    10    X
1    20    Y
2    30    Z

Slice of rows from index 1 onwards and column 'colB' (iloc):

1    Y
2    Z
Name: colB, dtype: object

## Summary:

### Data Analysis Key Findings

*   The DataFrame `m_df` has 3 rows and 2 columns, as indicated by the shape `(3, 2)`.
*   The DataFrame contains two columns: 'colA' (integer type, `int64`) and 'colB' (object type). Both columns initially have 3 non-null values.
*   Descriptive statistics were successfully generated for the numerical column 'colA', providing measures like count, mean, standard deviation, minimum, and maximum.
*   Integer-location based indexing (`iloc`) was used to select data by position, including single elements, rows, and slices of rows and columns.
*   Label-based indexing (`loc`) was used to select data by label, including single elements, rows, and slices of rows and columns. Label-based slicing with `loc` includes the end label.
*   The `dropna()` method effectively removed rows containing missing values after they were intentionally introduced into a copy of the DataFrame.
*   The `drop()` method successfully removed a specific row by its index (row 1) and a specific column by its name ('colB').
*   Slicing operations using both `iloc` (integer-location based) and `loc` (label-based) were demonstrated to select ranges of rows and columns.

### Insights or Next Steps

*   The various indexing and slicing methods (`iloc`, `loc`, basic indexing) provide flexible ways to access and manipulate subsets of data within the DataFrame.
*   Handling missing data using `dropna()` and modifying the DataFrame structure using `drop()` are essential steps in data cleaning and preparation.

In [ ]:
display(df_csv.head())

        colA      colB  Random_Column_1  Random_Column_2
0  10.000000         X               53               88
1  20.000000         Y               81               83
2  30.000000         Z               93               65
3   0.177001  0.648172               87               51
4   0.373451  0.523341                0               41

In [ ]:
display(df_csv.describe())

**Reasoning**:
Call the `describe()` method on the `df_csv` DataFrame and display the output to generate descriptive statistics as requested in the subtask.

## Apply `describe()`

### Subtask:
Generate descriptive statistics of the DataFrame.

In [ ]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   colA             5 non-null      float64
 1   colB             5 non-null      object
 2   Random_Column_1  5 non-null      int64
 3   Random_Column_2  5 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 292.0+ bytes

**Reasoning**:
Call the `.info()` method on the `df_csv` DataFrame to display a concise summary, including data types and non-null values as requested in the subtask.

## Apply `info()`

### Subtask:
Show a concise summary of the DataFrame, including data types and non-null values.

In [ ]:
print(df_csv.shape)

(5, 4)

**Reasoning**:
Access the `shape` attribute of the `df_csv` DataFrame to get its dimensions and print it as requested in the subtask.

## Get `shape`

### Subtask:
Display the dimensions (rows, columns) of the DataFrame.

# Task
Upload the current Colab notebook to GitHub and confirm that the notebook has been successfully uploaded.

## Upload to GitHub

### Subtask:
Upload the current Colab notebook to GitHub. This will typically involve saving the notebook and then pushing it to a specified GitHub repository.

## Upload to GitHub

### Subtask:
Upload the current Colab notebook to GitHub. This will typically involve saving the notebook and then pushing it to a specified GitHub repository.

#### Instructions
1. Go to 'File' in the Colab menu.
2. Select 'Save a copy in GitHub'.
3. In the dialog that appears, choose your GitHub repository and branch.
4. Add a meaningful commit message.
5. Click 'OK' to upload the notebook.

## Final Task

### Subtask:
Confirm that the notebook has been successfully uploaded to GitHub.

## Summary:

### Data Analysis Key Findings
*   The agent successfully provided detailed, numbered instructions for uploading a Colab notebook to GitHub. These instructions included navigating the Colab menu, selecting 'File' -> 'Save a copy in GitHub', choosing a GitHub repository and branch, and adding a commit message.
*   The subtask, which was to guide the user on how to upload the notebook, was completed successfully.

### Insights or Next Steps
*   The user should now follow the provided instructions to upload the current Colab notebook to their GitHub repository.